export const ICONS = [
    {
        labelKey: "category.food_dining",
        icons: [
            { name: "food", className: "icon-[mdi--food-variant]" },
            { name: "food-apple", className: "icon-[mdi--food-apple]" },
            {
                name: "food-fork-drink",
                className: "icon-[mdi--food-fork-drink]",
            },
            {
                name: "silverware-fork-knife",
                className: "icon-[mdi--silverware-fork-knife]",
            },
            { name: "cup", className: "icon-[mdi--cup]" },
            { name: "coffee", className: "icon-[mdi--coffee]" },
            { name: "glass-wine", className: "icon-[mdi--glass-wine]" },
            { name: "breakfast", className: "icon-[mdi--bread-slice]" },
            { name: "launch", className: "icon-[mdi--food-drumstick]" },
            { name: "dinner", className: "icon-[mdi--food-turkey]" },
            { name: "snack", className: "icon-[mdi--candy]" },
            { name: "treat", className: "icon-[mdi--noodles]" },
            { name: "drinks", className: "icon-[mdi--glass-cocktail]" },
        ],
    },
    {
        labelKey: "category.transport_travel",
        icons: [
            { name: "car", className: "icon-[mdi--car-side]" },
            { name: "car-electric", className: "icon-[mdi--car-electric]" },
            { name: "bus", className: "icon-[mdi--bus-side]" },
            { name: "train", className: "icon-[mdi--train-car]" },
            { name: "subway", className: "icon-[mdi--subway-variant]" },
            { name: "bike", className: "icon-[mdi--bike]" },
            { name: "airplane", className: "icon-[mdi--airplane]" },
            { name: "map", className: "icon-[mdi--map-marker-radius]" },
            { name: "map-marker", className: "icon-[mdi--map-marker-star]" },
            { name: "compass", className: "icon-[mdi--compass-rose]" },
            { name: "ticket", className: "icon-[mdi--ticket-confirmation]" },
            { name: "transport", className: "icon-[mdi--ferry]" },
            { name: "taxi", className: "icon-[mdi--taxi]" },
            { name: "parking", className: "icon-[mdi--parking]" },
            { name: "travel", className: "icon-[mdi--bag-suitcase]" },
        ],
    },
    {
        labelKey: "category.shopping_goods",
        icons: [
            { name: "cart", className: "icon-[mdi--cart-variant]" },
            { name: "cart-outline", className: "icon-[mdi--cart-outline]" },
            { name: "cart-plus", className: "icon-[mdi--cart-plus]" },
            { name: "basket", className: "icon-[mdi--basket]" },
            { name: "store", className: "icon-[mdi--store]" },
            { name: "storefront", className: "icon-[mdi--storefront-outline]" },
            { name: "bag-personal", className: "icon-[mdi--shopping]" },
            { name: "shopping", className: "icon-[mdi--shopping-outline]" },
            { name: "household", className: "icon-[mdi--home-variant]" },
            { name: "electronics", className: "icon-[mdi--devices]" },
            { name: "credits", className: "icon-[mdi--bitcoin]" },
            { name: "baby-and-mom", className: "icon-[mdi--baby-carriage]" },
            { name: "accessories", className: "icon-[mdi--watch-variant]" },
            { name: "office", className: "icon-[mdi--briefcase-variant]" },
        ],
    },
    {
        labelKey: "category.apparel_beauty",
        icons: [
            { name: "tshirt-crew", className: "icon-[mdi--tshirt-crew]" },
            { name: "shoe-sneaker", className: "icon-[mdi--shoe-sneaker]" },
            { name: "hanger", className: "icon-[mdi--hanger]" },
            { name: "lipstick", className: "icon-[mdi--lipstick]" },
            { name: "sunglasses", className: "icon-[mdi--sunglasses]" },
            { name: "face-woman", className: "icon-[mdi--face-woman-shimmer]" },
        ],
    },
    {
        labelKey: "category.housing_utilities",
        icons: [
            { name: "home", className: "icon-[mdi--home-variant]" },
            { name: "home-outline", className: "icon-[mdi--home-outline]" },
            { name: "lightbulb", className: "icon-[mdi--lightbulb-on]" },
            { name: "water", className: "icon-[mdi--water]" },
            { name: "gas-station", className: "icon-[mdi--gas-station]" },
            { name: "flash", className: "icon-[mdi--flash]" },
            { name: "housing", className: "icon-[mdi--office-building]" },
            {
                name: "electricity",
                className: "icon-[mdi--lightning-bolt]",
            },
            { name: "mgmt-fee", className: "icon-[mdi--flower]" },
            { name: "rent", className: "icon-[mdi--home-city]" },
            { name: "mortgage", className: "icon-[mdi--home-analytics]" },
            { name: "cleaning", className: "icon-[mdi--broom]" },
            { name: "renovation", className: "icon-[mdi--hammer-wrench]" },
        ],
    },
    {
        labelKey: "category.comm_internet",
        icons: [
            { name: "cellphone", className: "icon-[mdi--cellphone]" },
            { name: "wifi", className: "icon-[mdi--wifi]" },
            { name: "router", className: "icon-[mdi--router-wireless]" },
            { name: "server", className: "icon-[mdi--server-network]" },
            { name: "earth", className: "icon-[mdi--earth]" },
            { name: "phone", className: "icon-[mdi--phone-classic]" },
        ],
    },
    {
        labelKey: "category.medical_health",
        icons: [
            { name: "heart", className: "icon-[mdi--heart-pulse]" },
            { name: "hospital", className: "icon-[mdi--hospital-building]" },
            { name: "pill", className: "icon-[mdi--pill]" },
            { name: "stethoscope", className: "icon-[mdi--stethoscope]" },
            { name: "medical-bag", className: "icon-[mdi--medical-bag]" },
            { name: "medical", className: "icon-[mdi--hospital-box]" },
            { name: "clinic", className: "icon-[mdi--doctor]" },
            { name: "pharmacy", className: "icon-[mdi--pharmacy]" },
        ],
    },
    {
        labelKey: "category.education_learning",
        icons: [
            { name: "book", className: "icon-[mdi--book-open-page-variant]" },
            { name: "book-open", className: "icon-[mdi--book-open]" },
            { name: "school", className: "icon-[mdi--school]" },
            { name: "graduation-cap", className: "icon-[mdi--school-outline]" },
            { name: "education", className: "icon-[mdi--human-male-board]" },
            { name: "tuition", className: "icon-[mdi--account-school]" },
            { name: "books", className: "icon-[mdi--bookshelf]" },
            { name: "courses", className: "icon-[mdi--certificate]" },
        ],
    },
    {
        labelKey: "category.entertainment_leisure",
        icons: [
            { name: "camera", className: "icon-[mdi--camera]" },
            { name: "movie", className: "icon-[mdi--movie-open]" },
            { name: "music", className: "icon-[mdi--music-note]" },
            { name: "guitar", className: "icon-[mdi--guitar-acoustic]" },
            { name: "gamepad", className: "icon-[mdi--controller]" },
            { name: "dice-multiple", className: "icon-[mdi--dice-multiple]" },
            { name: "entertainment", className: "icon-[mdi--theater]" },
            { name: "movies", className: "icon-[mdi--filmstrip]" },
            { name: "fitness", className: "icon-[mdi--dumbbell]" },
            { name: "wellness", className: "icon-[mdi--spa]" },
            { name: "shows", className: "icon-[mdi--microphone-variant]" },
        ],
    },
    {
        labelKey: "category.pets",
        icons: [
            { name: "dog", className: "icon-[mdi--dog-side]" },
            { name: "cat", className: "icon-[mdi--cat]" },
            { name: "paw", className: "icon-[mdi--paw]" },
            { name: "fish", className: "icon-[mdi--fish]" },
            { name: "pets", className: "icon-[mdi--rabbit]" },
        ],
    },
    {
        labelKey: "category.social_gifts",
        icons: [
            { name: "gift", className: "icon-[mdi--gift]" },
            { name: "balloon", className: "icon-[mdi--balloon]" },
            { name: "party-popper", className: "icon-[mdi--party-popper]" },
            { name: "social", className: "icon-[mdi--account-group]" },
            {
                name: "family",
                className: "icon-[mdi--human-male-female-child]",
            },
            { name: "loan", className: "icon-[mdi--hand-coin]" },
            { name: "hongbao", className: "icon-[mdi--wallet-giftcard]" },
            { name: "Lean", className: "icon-[mdi--hand-extended]" },
        ],
    },
    {
        labelKey: "category.finance_wealth",
        icons: [
            { name: "wallet", className: "icon-[mdi--wallet]" },
            { name: "bank", className: "icon-[mdi--bank]" },
            { name: "cash", className: "icon-[mdi--cash-multiple]" },
            { name: "currency-usd", className: "icon-[mdi--currency-usd]" },
            { name: "currency-eur", className: "icon-[mdi--currency-eur]" },
            { name: "piggy-bank", className: "icon-[mdi--piggy-bank]" },
            { name: "chart-line", className: "icon-[mdi--chart-line]" },
            { name: "chart-pie", className: "icon-[mdi--chart-pie]" },
            { name: "shield", className: "icon-[mdi--shield-check]" },
            { name: "shield-check", className: "icon-[mdi--shield-star]" },
            { name: "security", className: "icon-[mdi--security]" },
            { name: "credit-card", className: "icon-[mdi--credit-card]" },
            {
                name: "credit-card-check",
                className: "icon-[mdi--credit-card-check]",
            },
            {
                name: "card-account-details",
                className: "icon-[mdi--card-account-details]",
            },
            { name: "wage", className: "icon-[mdi--cash-check]" },
            { name: "part-time", className: "icon-[mdi--briefcase-clock]" },
            { name: "fees-and-charges", className: "icon-[mdi--cash-minus]" },
            {
                name: "reconciliation",
                className: "icon-[mdi--credit-card-sync]",
            },
            { name: "refund", className: "icon-[mdi--credit-card-refund]" },
            { name: "drawback", className: "icon-[mdi--cash-refund]" },
        ],
    },
    {
        labelKey: "category.charity_donations",
        icons: [
            { name: "hand-heart", className: "icon-[mdi--hand-heart]" },
            { name: "hand-coin", className: "icon-[mdi--hand-coin-outline]" },
            { name: "account-heart", className: "icon-[mdi--account-heart]" },
            { name: "charity", className: "icon-[mdi--charity]" },
        ],
    },
    {
        labelKey: "category.others",
        icons: [
            {
                name: "dots-horizontal",
                className: "icon-[mdi--dots-horizontal-circle]",
            },
            { name: "help-circle", className: "icon-[mdi--help-circle]" },
            {
                name: "question-mark",
                className: "icon-[mdi--help-circle-outline]",
            },
            {
                name: "other-expenses",
                className: "icon-[mdi--folder-multiple]",
            },
        ],
    },
];
